image: openjdk:8

pipelines:
  branches:
    master:
      - step:
          name: Run tests
          caches:
            - gradle
          script:
            - bash ./gradlew test

      - step:
          name: Build and deploy artifact
          deployment: test
          script:
            - bash ./gradlew build
            - ls -l .
