image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - gradle
        script:
          - bash ./gradlew --no-daemon test

  branches:
    iss11:
      - step:
          name: Run tests
          caches:
            - gradle
          script:
            - bash ./gradlew --no-daemon test
      - step:
          name: Build artifact
          caches:
            - gradle
          script:
            - bash ./gradlew --no-daemon bootJar
          artifacts:
            - build/libs/*

